[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
external_url = "http://localhost:3000"
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
cookie_max_age = 86400

[edge_functions]
enabled = true
port = 54323

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.riot-api]
verify_jwt = true